# Generated by Django 3.2.4 on 2021-06-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('venda_concluida', models.BooleanField()),
                ('numero_venda', models.IntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=10, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branco', models.BooleanField()),
                ('preto', models.BooleanField()),
                ('vermelho', models.BooleanField()),
                ('azul', models.BooleanField()),
                ('amarelo', models.BooleanField()),
                ('verde', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('numero_venda', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('numero_venda', models.IntegerField()),
                ('cor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volkswagen', models.BooleanField()),
                ('chevrolet', models.BooleanField()),
                ('toyota', models.BooleanField()),
                ('honda', models.BooleanField()),
                ('hyundai', models.BooleanField()),
                ('peugeot', models.BooleanField()),
                ('numero_venda', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modo_pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venda', models.IntegerField()),
                ('nome', models.CharField(max_length=10)),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('valor', models.DecimalField(decimal_places=1, max_digits=10)),
                ('hora_venda', models.TimeField(auto_now_add=True)),
                ('data_venda', models.DateField(auto_now_add=True)),
                ('comprovante_da_venda', models.FileField(upload_to='comprovante_venda/')),
                ('venda_concluida', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pontos_de_avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venda', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comentario', models.TextField(blank=True, default=10)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('data', models.DateField(blank=True)),
                ('hora', models.TimeField(blank=True)),
                ('numero_venda', models.IntegerField()),
            ],
        ),
    ]
